export type LegalSection = {
  title: string;
  body: string;
};

export const privacyPolicySections: LegalSection[] = [
  {
    title: "rizzora.ai Privacy Policy",
    body:
      "This Privacy Policy describes how VOCOSMOS PTE. LTD. and its affiliates collect, use, store, disclose and protect your personal information. It applies to the rizzora.ai website, mobile applications and other services that link to this Policy. The Services currently provide text-based interactions only and do not collect voice or video data."
  },
  {
    title: "Special Notice",
    body:
      "EU/UK users should also refer to the EU/UK-specific provisions in this Policy. U.S. users, especially California users, should also refer to the U.S.-specific provisions in this Policy."
  },
  {
    title: "1. Information We Collect",
    body:
      "We collect information based on how you use the Services, including identifiers, demographic information, interest preferences, account settings, character preferences, payment information processed by third-party providers, chat content and other content generated through interaction with the Services. We may also collect device and usage data, interaction behavior, cookies and similar technologies, third-party login information from Apple, Google or Facebook, and publicly available data used only for service improvement and in compliance with applicable law."
  },
  {
    title: "2. How We Use Information",
    body:
      "We use information to provide, maintain and personalize the Services, improve AI models and algorithms, process subscriptions, payments and Credits purchases, protect service security, prevent fraud and abuse, comply with legal obligations, and communicate service notices or policy updates. Marketing communications are sent only with your consent where required."
  },
  {
    title: "3. Generative AI-Related Use",
    body:
      "To improve service quality and AI model performance, your chat content, preferences and interaction data may be used for model training and optimization. We prefer anonymized or aggregated processing. If you wish to stop new data from being used for training, you may delete your account. Data already used for training and anonymized cannot be fully removed from trained models."
  },
  {
    title: "4. When We Disclose Information",
    body:
      "We may disclose information to necessary service providers, when required by law or court order, to protect rights and safety, in connection with a business transfer, or with your explicit consent. We do not sell your personal data."
  },
  {
    title: "5. Your Rights and Choices",
    body:
      "Depending on your location, you may have rights to access, correct, delete, restrict or object to processing of your personal information, request data portability, withdraw consent, and opt out of marketing communications. To exercise your rights, use account settings where available or email support@rizzora.ai."
  },
  {
    title: "6. Data Security and Retention",
    body:
      "We implement reasonable technical and organizational measures including encryption, access controls and regular security assessments. Account information is retained during the account life and for a reasonable period after closure. Chat records are retained while needed to provide memory features. Payment records are retained as required by tax and accounting laws."
  },
  {
    title: "7. International Data Transfers",
    body:
      "Your data may be transferred to locations outside Singapore, including regions where our cloud service providers operate. We use appropriate mechanisms such as Standard Contractual Clauses, adequacy decisions or other legally recognized safeguards where required."
  },
  {
    title: "8. Children's Protection",
    body:
      "The Services are intended solely for users aged 18 and above. We do not knowingly collect personal information from individuals under 18. If we become aware that such information has been collected, we will delete it promptly and terminate the corresponding account where appropriate."
  },
  {
    title: "9. Contact Us",
    body: "Email: support@rizzora.ai\nCompany: VOCOSMOS PTE. LTD.\nSingapore"
  }
];

export const termsOfServiceSections: LegalSection[] = [
  {
    title: "rizzora.ai Terms of Service",
    body:
      "Effective Date: July 2026. These Terms of Service constitute a legal agreement between you and VOCOSMOS PTE. LTD. and its affiliates. By using our Services, you agree to these Terms. If you do not agree, please stop using the Services immediately."
  },
  {
    title: "1. Description of Services",
    body:
      "rizzora.ai provides AI-powered virtual male character text companionship services designed to offer emotional support, personalized conversation and companionship experiences. The Services are generated by artificial intelligence. Characters are not real humans and are not a substitute for real human relationships, professional psychological counseling, medical, legal or other professional advice."
  },
  {
    title: "2. Eligibility",
    body:
      "You must be at least 18 years of age, or the age of majority in your country or region, whichever is higher, to use the Services. Individuals under 18 are strictly prohibited from using the Services."
  },
  {
    title: "3. User Accounts",
    body:
      "You must provide true, accurate and complete information when registering an account and keep it updated. You are responsible for maintaining account security and for all activities under your account. We may suspend, restrict or terminate your account if you violate these Terms, engage in fraud or abuse, provide false age information, or as required by law."
  },
  {
    title: "4. User Content and Conduct",
    body:
      "You are responsible for all content you input. You must not input or attempt to induce generation of content that is illegal, harmful, harassing, hateful, violent, pornographic involving minors, infringing, fraudulent or otherwise in violation of applicable law or these Terms."
  },
  {
    title: "5. Intellectual Property",
    body:
      "The Services, AI models, character settings, interface design, generated content other than your input content, and related intellectual property rights belong to rizzora.ai or its licensors. Without written permission, you may not copy, modify, distribute, reverse engineer or commercially use the Services."
  },
  {
    title: "6. Payments and Subscriptions",
    body:
      "The Services may operate on an auto-renewing subscription model and may offer Credits for users to purchase additional conversation access. Specific prices, payment methods, auto-renewal rules, cancellation methods, Credit usage rules and refund policies are set out in the Payment Terms and Refund Policy."
  },
  {
    title: "7. Prohibited Conduct",
    body:
      "You agree not to use the Services for illegal, harmful, harassing, bullying, infringing or fraudulent purposes; interfere with or disrupt service operation; circumvent security restrictions; use bots or scrapers; impersonate others; misrepresent identity or age; or induce AI to generate content that violates these Terms or applicable law."
  },
  {
    title: "8. Disclaimer",
    body:
      "The Services are provided on an as-is and as-available basis. We do not warrant that the Services will be uninterrupted, error-free, completely secure or meet your specific requirements. AI output may be inaccurate or unsuitable and does not constitute professional advice."
  },
  {
    title: "9. Limitation of Liability",
    body:
      "To the maximum extent permitted by law, rizzora.ai and its affiliates, directors and employees shall not be liable for indirect, incidental, special, consequential or punitive damages arising from the use of or inability to use the Services. Our total liability shall not exceed the total amount of fees you paid to us in the 12 months preceding the claim, or zero if no payment was made."
  },
  {
    title: "10. Termination",
    body:
      "You may stop using the Services and delete your account at any time. We may terminate or suspend the Services or your account due to violations, prolonged inactivity, false information, legal requirements or business adjustments."
  },
  {
    title: "11. Governing Law and Dispute Resolution",
    body:
      "These Terms are governed by the laws of Singapore. Disputes should first be resolved through friendly negotiation. If negotiation fails, disputes may be submitted to the Singapore International Arbitration Centre in Singapore, subject to statutory consumer rights that cannot be waived."
  },
  {
    title: "12. Contact Us",
    body: "Email: support@rizzora.ai\nCompany: VOCOSMOS PTE. LTD.\nSingapore"
  }
];

export const paymentTermsSections: LegalSection[] = [
  {
    title: "rizzora.ai Payment Terms",
    body: "Effective Date: July 2026. These Payment Terms explain the current non-member experience, VIP membership, subscription plans, Credits purchases and the relationship between membership benefits and Credits."
  },
  {
    title: "1. Non-Member Experience",
    body:
      "Non-member users may have 30 free text conversations with digital characters. Once the limit is reached, users must upgrade to VIP membership or purchase Credits to continue chatting."
  },
  {
    title: "2. VIP Membership",
    body:
      "VIP Membership unlocks text conversations, memory capabilities and a companionship experience within the bounds of reasonable use. Current main benefits include heartwarming message replies and excellent memory capability, subject to technical and reasonable use limitations."
  },
  {
    title: "3. Subscription Plans",
    body:
      "We offer flexible auto-renewing subscription plans that may be cancelled at any time. Monthly: first period $9.95, original $19.9. Quarterly: first period $24.95, original $58. Yearly: first period $89.95, original $179.9. Unless cancelled in advance, subscriptions automatically renew at the end of each period at the regular price shown on the checkout page."
  },
  {
    title: "4. Credits",
    body:
      "Credits may be used to redeem additional text conversation turns. Credits are credited to the account after purchase and may be used for conversations on the current account. Credits are non-transferable, non-redeemable for cash, and may only be used within the rizzora.ai Services."
  },
  {
    title: "5. Relationship Between VIP and Credits",
    body:
      "VIP members enjoy membership benefits within the bounds of reasonable use during the subscription period. After membership benefits are exhausted, users may choose to purchase Credits to continue conversations. Credits and VIP subscriptions are independent. Purchasing Credits does not automatically extend or affect the VIP subscription period."
  },
  {
    title: "6. Refund Rules",
    body:
      "Please see the Refund Policy. After a subscription is activated and after Credits are purchased, refunds are generally not provided except where required by law or expressly provided in the applicable policy."
  }
];

export const refundPolicySections: LegalSection[] = [
  {
    title: "rizzora.ai Refund Policy",
    body:
      "Effective Date: July 2026. We are committed to providing quality AI companionship services. To ensure fairness and sustainable operations, subscriptions and Credits are generally non-refundable once purchased, except where required by law or expressly provided in this Policy."
  },
  {
    title: "1. Subscription Refund Rules",
    body:
      "After a subscription is activated, the remaining subscription period is generally non-refundable whether used or unused. Yearly, quarterly and monthly plans are not refunded on a pro-rata basis. In rare verified cases, such as a major technical failure on our side that renders the Services completely unusable for more than 72 consecutive hours or a clear duplicate charge error, we may handle a refund at our discretion."
  },
  {
    title: "2. Credit Refund Rules",
    body:
      "Credits are virtual goods and are credited immediately upon successful purchase. Consumed Credits and unused Credits are generally non-refundable. If a system fault causes Credits not to be credited correctly or to be deducted in error, we may, after verification, reissue the corresponding Credits or process a refund."
  },
  {
    title: "3. Exceptions and Legal Requirements",
    body:
      "Where applicable law requires a mandatory right of refund, we will process refunds in accordance with the law. If an account is restricted or banned due to violation of the Terms of Service, fees paid and Credits will not be refunded except where required by law."
  },
  {
    title: "4. Refund Process",
    body:
      "Submit a refund request to support@rizzora.ai with the order number, reason for the refund and relevant screenshots. We will review the request within a reasonable time. Processing generally takes 5 to 14 business days. If approved, the amount will be returned through the original payment method."
  },
  {
    title: "5. Canceling a Subscription",
    body:
      "You may cancel your subscription at any time in account settings. After cancellation, no new charges will be incurred, but the current paid period is non-refundable. Cancellation does not affect already unlocked benefits until the end of the current period."
  },
  {
    title: "6. Final Provisions",
    body:
      "We reserve the right to interpret refund requests and may adjust this Policy in accordance with applicable law. All refunds are based on platform records. Submitting a refund request does not guarantee that a refund will be granted."
  }
];

export const dataAuthorizationSections: LegalSection[] = [
  {
    title: "Data Authorization Statement",
    body:
      "Effective Date: July 2026. This Statement clearly informs you of the scope and manner of your authorization for our processing of related data when using the rizzora.ai Services. It supplements the Privacy Policy and, together with the Privacy Policy and Terms of Service, forms the data processing framework."
  },
  {
    title: "1. Third-Party Login Authorization",
    body:
      "When you choose to sign in with a third-party account such as Apple, Google or Facebook, you authorize us to obtain and use the basic profile information provided by that third party, such as name, avatar, email and account identifier, subject to your authorization settings on the third-party platform. We use such information only for account creation, login verification, profile display and service security."
  },
  {
    title: "2. User Input Content Authorization",
    body:
      "For chat content, preference settings and other interactive content you input, you grant us a worldwide, non-exclusive, royalty-free, transferable license to use, reproduce, modify and distribute such content within the scope of providing, maintaining and improving the Services. You retain ownership of your own input content."
  },
  {
    title: "3. AI Model Training Authorization",
    body:
      "To continuously improve the AI companionship experience and model quality, your chat content, preferences and interaction data may be used for model training and optimization. We prefer anonymized or aggregated processing. By using the Services, you understand and agree to this use."
  },
  {
    title: "4. Withdrawal and Changes of Authorization",
    body:
      "You may withdraw authorization for future data processing by deleting your account. Withdrawal does not affect processing already carried out on a lawful basis before withdrawal. Where the law requires additional consent, we will obtain it separately."
  },
  {
    title: "5. Contact",
    body: "Email: support@rizzora.ai\nCompany: VOCOSMOS PTE. LTD.\nSingapore"
  }
];
